# Generated by Django 3.1.7 on 2021-04-28 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_citizen_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='citizen',
            name='mobno',
            field=models.CharField(max_length=256, unique=True),
        ),
    ]
