# Generated by Django 3.1.7 on 2021-04-30 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20210430_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='citizen',
            name='centername',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='main.vac_center'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citizen',
            name='city',
            field=models.CharField(choices=[('Nagpur', 'Nagpur'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune')], max_length=256),
        ),
        migrations.AlterField(
            model_name='citizen',
            name='timeslot',
            field=models.CharField(choices=[('2pm to 6pm', '2pm to 6pm'), ('10am to 1am', '10am to 1am')], max_length=256),
        ),
        migrations.AlterField(
            model_name='vac_center',
            name='city',
            field=models.CharField(choices=[('Nagpur', 'Nagpur'), ('Mumbai', 'Mumbai'), ('Pune', 'Pune')], max_length=256),
        ),
    ]
